### ISSUE TITLE
Ignore extra master Merchant addons

### ISSUE THREAD

**Issue by Findarato** [Trojan295/eso-addons#10]
I am moving from Minion 3 to your tool and I am super afraid of removing unused because of the MM data.  Is there a way to ignore the extra data files?

MM01Data-MM14Data

**Comment by Trojan295** [comment]
Hey @Findarato!

Is this `MM01Data-MM14Data` an addon or just a directory? If it's a normal addon, but installed manually you can add the following entry to the `eso-addons.toml`:

```toml
[[addons]]
name = "MM01Data-MM14Data"
dependency = false
```

After that it should be seen as a manually normal addon and not garbage collected:
```bash
$ eso-addons list
+-------------------+-----------+
| Name              | Status    |
+-------------------+-----------+
| MM01Data-MM14Data | INSTALLED |
+-------------------+-----------+

$ eso-addons clean
Nothing to clean
```

**Comment by Trojan295** [comment]
Closing this as there is not response from @Findarato
