### ISSUE TITLE
Failed to execute: while downloading <addon>: while reading addon: Not a directory

### ISSUE THREAD

**Issue by Lordakius** [Trojan295/eso-addons#2]
I cloned the project, copied the example eso-addons.toml and changed the directory according to my setup. But when I run `eso-addons update` it installs most of the entries but fails at LibChatMessage

`Failed to execute: while downloading LibChatMessage: while reading addon: Not a directory (os error 20)`

Strangely, all other addons are downloading as intended (and I can see their files in the Addons dir). I also checked ingame and surprisingly, it recognizes all addons up to and including libChatMessage, but not the ones after that. 

looking through the code, the error gets created in addons.rs on line 35, but my Rust is rusty (pun intended), so I am not quite sure why read_dir fails. 

is this a known error or is there a workaround for it? If i get around I can write one up and make a PR, is this repo still actively used or should i fork?

**Comment by Trojan295** [comment]
Hello! What OS are you using? Could you provide a listing of the addon directories?

If you can solve this on your own, you are welcome to send a PR for this!

**Comment by Lordakius** [comment]
woops, i totally forgot to add some additional info xD here u go

OS: Pop!_OS 20.10

This is inside /users/steamuser/My Documents/Elder Scrolls Online/live/Addons
`AutoHandleSharedQuests, CustomCompassPins, LibAddonMenu-2.0, LibChatMessage,
LibDebugLogger, LibGPS, LibMapPing, LibMapPins-1.0, SkyShards`

and the config (in txt, cuz github didnt like the toml extension)

[eso-addons.txt](https://github.com/Trojan295/eso-addons/files/6366029/eso-addons.txt)

I kinda got around the issue by just moving the LibChatMessage entry to the bottom, so it installed all addons, then threw an error but it still (apparently) installed everything. This would work until there are 2 entries throwing errors i guess.

**Comment by Trojan295** [comment]
@Lordakius , could you check, if https://github.com/Trojan295/eso-addons/pull/3 fixes your problem?

**Comment by Lordakius** [comment]
yes, the PR fixes the error. thanks alot !
