### ISSUE TITLE
backtrace installing LibHistoire

### ISSUE THREAD

**Issue by pjz** [Trojan295/eso-addons#20]
Trying to install the 'LibHistoire' lib for MM, got this:

```
$ eso-addons add 'https://www.esoui.com/downloads/fileinfo.php?id=2817'
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/cli/add.rs:38:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I'm presuming this is easily reproducible by you; if not, let me know and I can provide the full backtrace.

**Comment by Trojan295** [comment]
Hello @pjz. Right now, only the link matching [this regex](https://github.com/Trojan295/eso-addons/blob/7b1730a31e959ddf01f205627c6a7bcd6f0eb8ff/src/cli/add.rs#L141) are supported: `^https://.*esoui.com/downloads/info(\d+)-(.+)\.html$`
```bash
eso-addons add https://www.esoui.com/downloads/info2817-LibHistoire-GuildHistory.html`
```

**Comment by pjz** [comment]
Hmm.  I got that link from the MM page - could you perhaps attempt to automatically remap the URL since you seem to know how?  Or at least add an error message saying "we only match this regex" instead of panicking?
