### ISSUE TITLE
Add-on directory permissions error

### ISSUE THREAD

**Issue by arviceblot** [Trojan295/eso-addons#23]
## Problem

While attempting to install LuiExtended, the following error occurs:

```shell
❯ eso-addons add https://www.esoui.com/downloads/info818-LuiExtended.html
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/addons.rs:182:62
```

It seems this is related to a permissions issue with a directory in the archive:

```shell
❯ ls -l LuiExtended/media/icons/ 
total 0
dr-xr-xr-x  2 arviceblot  staff  64 Jan  4 20:32 abilities
```

I'm not sure why the archive is created this way, but it leads the directory to be created as unwritable, causing the permission error when writing additional files for it.

## Potential solutions

* Apply unix file permissions after all files are written. I'm not really a fan of this because you would have to store permissions for all file as the archive is iterated.
* Use default permissions for directories to ensure they are writable. Also not a big fan of this because of hardcoding permissions.

### P.S.

@Trojan295 I would love your feedback on this. I really enjoy the spirit of this program, as it means I don't have to use Minion :P

**Comment by Trojan295** [comment]
The packaging of the zip is a bit strange. If I unzip it and then try to delete, I get `permission denied` errors also, as there are no write permissions on the files. So if, we change the permissions to the ones in the zip after unzipping all, then we would have problems, when removing the addon.

I think the way to go, is to ensure that all files have write permissions. I don't see any use case, where a read-only permission for a file would make sense. This should be an easy fix, just removing this block, which sets unix permissions:
https://github.com/Trojan295/eso-addons/blob/24ac0ded7252e6ebb103583c7c50524e07250f56/src/addons.rs#L188
