### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by wabkia** [Trojan295/eso-addons#4]
I love it! just like cursebreaker. i couldn't get minion to work. i think it had some issue with the install dir. I have a few suggestions :)

> should be able to handle 'infoXXXX' page links. in the interim, let users know they need to use the 'downloadXXXX' link from that page. -- i see i missed the current instructions in the example config!

> should be able to handle drives in windows, C:\ etc. in the interim, let windows users know they can use addonDir = "/users/[account]/Documents/Elder Scrolls Online/live/AddOns" in the config file -- added link to suggested change below

> current directory isnt checked for .eso-addons.toml on windows. in the interim, let windows users know they should specify a config file --config c:\path\to\.eso-addons.toml every time they use eso-addons.

> package exe in .zip, naming the zip with the version and keeping eso-addons.exe inside?

**Comment by wabkia** [comment]
#https://github.com/Trojan295/eso-addons/compare/master...wabkia:patch-1

**Comment by Trojan295** [comment]
Hey! Thanks for the suggestions! Unfortunately, I'm not using Windows, so it will be tricky for me to test some changes. Just to understand:

> should be able to handle drives in windows, C:\ etc. in the interim, let windows users know they can use addonDir = "/users/[account]/Documents/Elder Scrolls Online/live/AddOns" in the config file -- added link to suggested change below

AFAIK normally the path to the addons dir (with the drive letter) is `C:\Users\[account]\Documents\Elder Scrolls Online\live\AddOns`. Does Powershell/cmd also support `/Users/[account]/Documents/Elder Scrolls Online/live/AddOns`?

> current directory isnt checked for .eso-addons.toml on windows. in the interim, let windows users know they should specify a config file --config c:\path\to.eso-addons.toml every time they use eso-addons.

You should be able to create the config file in `C:\Users\[account]\.eso-addons.toml`. The binary looks for the config file (on all OSes) only in the home directory. Your current working directory does not matter.

**Comment by wabkia** [comment]
i believe rust is doing the interpretation on the addonDir string and translating it into something windows understands. i figured this out trying out different things, 'why would it compile and not be able to interact with the storage device, its 2021!' was my thinking. powershell will auto-complete with '/', correcting them to '\', but im fairly sure it cant use /paths/to/something. to make things easy, i run with a command script, which uses command prompt by default which i am also fairly sure isnt doing anything special.  in either case, when providing the proper windows path, we receive the error below. line 3 is where addonDir is and im assuming the 's' is from the trailing \AddOns" before the ending quote.

> Failed to execute: invalid hex escape character in string: `s` at line 3

during my initial testing, i had attempted to escape using double quotes and 'C/:/\users'. i realized my error and removed the escape from the '/:' and voila, it worked :)

> 'C:/\users/\[account]/\Documents/\Elder/ Scrolls/ Online/\live/\AddOns'

probably, this can still be fixed? low priority.

looking in the home dir is fine on *nix, but on windows CWD does matter. i know you probably dont care :P theres no /usr/local/bin on windows, so the executable will likely go to in whatever folder the user decides with the config file next to it. probably not high priority as long as the user knows all this. seems like it wouldnt be difficult to check both places, covering a core use case for windows.

i love this tool. just like cursebreaker, avoiding unnecessary zip management and bloated software! THANK YOU!!!!

**Comment by Trojan295** [comment]
I tried to use 

```
addonDir = "C:/Users/Administrator/addons"
```

and it worked without any issues. I didn't need to escape anything.

**Comment by wabkia** [comment]
i didn't even think to try that. the same string works in file explorer. its a new dawn for windows!

seems like an update to the note should close this out then.

**Comment by Trojan295** [comment]
I'm preparing a bigger update with interactive commands to add/remove addons, which will support the `infoXXXX` links. I merged your branch with the note in the config, thank you!

@wabkia can I close this issue? If you have any other ideas for improvements/problems, don't hesitate to create separate issues for this. :)

**Comment by Trojan295** [comment]
Closing this, as there is not response from @wabkia .
