### ISSUE TITLE
Addon installation error

### ISSUE THREAD

**Issue by zelenin** [Trojan295/eso-addons#52]
```
PS C:\Users\aleks> eso-addons-x86_64-pc-windows-msvc.exe add https://www.esoui.com/downloads/info3034-HarvestMap-Data.html
app error: cannot read addon HarvestMapData: missing addon metadata file
```

**Comment by arviceblot** [comment]
I believe that is just the data downloader scripts for the main HarvestMap addon. It doesn't have any actual addon information. I had to manually install this one, then run the DownloadNewData script.
